name: bikretaa
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  pin_code_fields: ^8.0.1
  email_validator: ^3.0.0
  google_fonts: ^6.3.0
  animated_custom_dropdown: ^3.1.1
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.3
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  http: ^1.4.0
  intl: ^0.20.2
  image_picker: ^1.2.0
  palette_generator: ^0.3.3+7
  shimmer: ^3.0.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/


