name: bikretaa
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  pin_code_fields: ^8.0.1
  email_validator: ^3.0.0
  google_fonts: ^6.3.0
  animated_custom_dropdown: ^3.1.1
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.3
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  http: ^1.4.0
  intl: ^0.20.2
  image_picker: ^1.2.0
  palette_generator: ^0.3.3+7
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.0
  carousel_slider: ^5.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  device_preview: ^1.3.1
  get: ^4.7.2
  math_expressions: ^2.4.0
  table_calendar: ^3.2.0
  mobile_scanner: ^7.1.3
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  converter: ^0.4.0
  crypto: ^3.0.7
  encrypt: ^5.0.3
  syncfusion_flutter_charts: ^28.2.7
  pdf: ^3.10.7
  printing: ^5.11.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1+3
  flutter_local_notifications: ^17.2.2
  get_storage: ^2.1.1
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/app_logo.png"
    adaptive_icon_background: "assets/images/white.png"
    adaptive_icon_foreground: "assets/images/app_icon_B.png"



flutter:


  uses-material-design: true


  assets:
    - assets/images/


